export enum WsMessageType {
  JOIN_QUEUE = "JOIN_QUEUE",
  MATCH_FOUND = "MATCH_FOUND",
  CHAT_MESSAGE = "CHAT_MESSAGE",

  PEER_RECONNECTING = "PEER_RECONNECTING",
  PEER_RECONNECTED = "PEER_RECONNECTED",
  PEER_DISCONNECTED = "PEER_DISCONNECTED",
  FIND_ANOTHER_MATCH = "FIND_ANOTHER_MATCH",
  END_CONVERSATION = "END_CONVERSATION",
  END_CHAT = "END_CHAT",
  TYPING_START = "TYPING_START",
  TYPING_STOP = "TYPING_STOP",
  RESUME_CONVERSATION = "RESUME_CONVERSATION",
  REQUEST_RESUME = "REQUEST_RESUME",
  INVALID_CONVERSATION_ID = "INVALID_CONVERSATION_ID"

  }
  
  export interface ChatPayload {
    message: string;
    from :string;
  }
  